; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35721.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	_CxxThrowException:PROC
EXTRN	__CxxFrameHandler4:PROC
EXTRN	__GSHandlerCheck_EH4:PROC
EXTRN	memcpy:PROC
EXTRN	strlen:PROC
EXTRN	__security_cookie:QWORD
EXTRN	_fltused:DWORD
END
