; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35721.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
msvcjmc	SEGMENT
__ED5CB687_concurrencysal@h DB 01H
__E45EDB60_sal@h DB 01H
__D35E0FCE_vadefs@h DB 01H
__C27BE271_vcruntime@h DB 01H
__26A6A76C_xkeycheck@h DB 01H
__E31B3605_yvals_core@h DB 01H
__15254F97_limits@h DB 01H
__6D608555_climits DB 01H
__62CE13B5_xtr1common DB 01H
__D889C389_intrin0@inl@h DB 01H
__7C8A1759_intrin0@h DB 01H
__C395D46E___msvc_bit_utils@hpp DB 01H
__CAE7E606___msvc_sanitizer_annotate_container@hpp DB 01H
__AB5361A8_stdint@h DB 01H
__54D146DA_cstdint DB 01H
__735960E1_corecrt@h DB 01H
__1D9A7FA2_corecrt_math@h DB 01H
__2E93F1C0_math@h DB 01H
__211DB995_corecrt_malloc@h DB 01H
__955456CD_stddef@h DB 01H
__99AED4FB_corecrt_search@h DB 01H
__8B813BF6_corecrt_wstdlib@h DB 01H
__E8FB0A68_stdlib@h DB 01H
__E98FA7A7_cstdlib DB 01H
__CB8A55F3_float@h DB 01H
__0B520893_cfloat DB 01H
__60B45B40_corecrt_stdio_config@h DB 01H
__CFA3741E_corecrt_wstdio@h DB 01H
__B3FE3303_stdio@h DB 01H
__7816C314_cstdio DB 01H
__13DE2371_errno@h DB 01H
__913C9CB3_vcruntime_string@h DB 01H
__8ACB2152_corecrt_memcpy_s@h DB 01H
__8BDC0229_corecrt_wconio@h DB 01H
__108B2620_corecrt_wctype@h DB 01H
__547F429B_corecrt_wdirect@h DB 01H
__260A2221_corecrt_share@h DB 01H
__EB642103_corecrt_wio@h DB 01H
__F49D648E_corecrt_wprocess@h DB 01H
__0DF2AF52_corecrt_wstring@h DB 01H
__9E5BC8DA_corecrt_wtime@h DB 01H
__2A5E3E75_types@h DB 01H
__B16B2B9B_stat@h DB 01H
__3B3089AB_setjmp@h DB 01H
__5CE08A7F_mmintrin@h DB 01H
__7CD62D9E_malloc@h DB 01H
__42AE8E25_xmmintrin@h DB 01H
__27CC07E9_emmintrin@h DB 01H
__F86D6F60_pmmintrin@h DB 01H
__48B41CE2_tmmintrin@h DB 01H
__618F0961_smmintrin@h DB 01H
__04ED80AD_nmmintrin@h DB 01H
__D1567AE3_wmmintrin@h DB 01H
__1AC237E4_zmmintrin@h DB 01H
__2DD6952E_immintrin@h DB 01H
__9715746B_ammintrin@h DB 01H
__1D0635DC_intrin@h DB 01H
__4DD8D0FE_wchar@h DB 01H
__E29D1547_cwchar DB 01H
__6DB445F7_limits DB 01H
__9A5272F0_vcruntime_new@h DB 01H
__42867C4A_vcruntime_new_debug@h DB 01H
__15FC02C9_crtdbg@h DB 01H
__65A7AE52_crtdefs@h DB 01H
__99C021FC_use_ansi@h DB 01H
__5FCF1118_yvals@h DB 01H
__4C447D0A_cstddef DB 01H
__680F61A7_type_traits DB 01H
__C071288D_corecrt_terminate@h DB 01H
__7747910A_eh@h DB 01H
__4A687918_vcruntime_exception@h DB 01H
__ADF8C0C4_exception DB 01H
__EBEDE495_new DB 01H
__A7F44C12_xatomic@h DB 01H
__F79AC0B4_initializer_list DB 01H
__4323F09F_concepts DB 01H
__109A9D16_compare DB 01H
__DE82222C_utility DB 01H
__B73D1048___msvc_iter_core@hpp DB 01H
__EA6C9D17_corecrt_memory@h DB 01H
__6E889ECC_string@h DB 01H
__A51D0F47_cstring DB 01H
__C78B1955_xutility DB 01H
__20C7CC96_tuple DB 01H
__B41741EF_xmemory DB 01H
__3ABE9893_xpolymorphic_allocator@h DB 01H
__20193517_vector DB 01H
__A15D9071_iosfwd DB 01H
__FEA281E8___msvc_string_view@hpp DB 01H
__C0C4C773_xstring DB 01H
__6CD6613D_ctype@h DB 01H
__77DD24B3_cctype DB 01H
__A5C9CFE5_string DB 01H
__17A06EC7_Value@h DB 01H
__A3D3F6D7_vcruntime_typeinfo@h DB 01H
__B754EA4C_typeinfo DB 01H
__D91C7F2A_xatomic_wait@h DB 01H
__EEAFAE40___msvc_threads_core@hpp DB 01H
__1FF36214_time@h DB 01H
__405749DF_ctime DB 01H
__714FFA14_xtimec@h DB 01H
__F88E164F_xthreads@h DB 01H
__06811935_atomic DB 01H
__D11A4979_memory DB 01H
__A7ECD5BA_Document@h DB 01H
__1D002934_Writer@h DB 01H
__8AF791B0_Writer@cpp DB 01H
msvcjmc	ENDS
PUBLIC	__JustMyCode_Default
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
END
